### ISSUE TITLE
模糊搜索没效果

### ISSUE THREAD

**Issue by muzidudu** [JimChenWYU/laravel-scout-xunsearch#1]
希望修复一下
`search($slug)->where('fuzzy',new FuzzyOperator(true))->paginate(20)`
不知道我这样写法对不对

**Comment by JimChenWYU** [comment]
@muzidudu 抱歉，现在才看到，能否提供一下简化后的搜索数据

**Comment by muzidudu** [comment]
fuzzy需要在search()前面执行才有效果
`$search->setFuzzy()->search('上海公园');`
参考[http://xunsearch.com/doc/php/guide/search.query](url)

**Comment by JimChenWYU** [comment]
@muzidudu

**Comment by JimChenWYU** [comment]
发了新的测试版

https://github.com/JimChenWYU/laravel-scout-xunsearch/releases/tag/0.2.2-alpha
